# Generated by Django 4.2.1 on 2023-05-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resgistrado',
            new_name='Registrado',
        ),
    ]
